org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.3
java_version=25

mod_id=anvil_insight
fabric_mod_id=anvil-insight
quilt_mod_id=anvil-insight
mod_name=Anvil Insight
mod_version=1.1+mc26.3
maven_group=anvilinsight
mod_license=CC0-1.0

fabric_loader_version=0.19.5
fabric_loom_version=1.17.21
fabric_api_version=0.161.0+26.3
fabric_resource_loader_version=3.0.4
mixin_version=0.17.4+mixin.0.8.7

quilt_loader_version=0.31.0-beta.4
neoforge_version=26.3.0.33-beta
moddevgradle_version=2.0.147

forge_version=26.3-66.0.8
forgegradle_version=7.0.17
forge_loader_version_range=[66,)
